#!/usr/bin/env bash
# creates a file /var/run/myscript.pid
# Displays to infinity and beyond indefinitely
# Displays "I hate the kill command"

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do 
	echo "To infinty and beyound"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
